# Generated by Django 4.2.2 on 2023-06-10 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_name', models.CharField(max_length=200, unique=True)),
                ('vid_link', models.TextField(unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_body', models.BooleanField(default=False)),
                ('lower_body', models.BooleanField(default=False)),
                ('barbell', models.BooleanField(default=False)),
                ('dumbbell', models.BooleanField(default=False)),
                ('kettlebell', models.BooleanField(default=False)),
                ('olympic', models.BooleanField(default=False)),
                ('power', models.BooleanField(default=False)),
                ('strength', models.BooleanField(default=False)),
                ('arms', models.BooleanField(default=False)),
                ('chest', models.BooleanField(default=False)),
                ('shoulders', models.BooleanField(default=False)),
                ('back', models.BooleanField(default=False)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movelibrary.movementlibrary')),
            ],
        ),
    ]
