# Generated by Django 4.2.2 on 2023-07-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movelibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='thumbnail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
