# Generated by Django 4.2.2 on 2023-06-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movelibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementlibrary',
            name='vid_link',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
