# Generated by Django 4.2.2 on 2023-06-10 13:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movelibrary', '0002_alter_movementlibrary_vid_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovementLibrary',
            new_name='Movement',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
