# Generated by Django 4.2.2 on 2023-07-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movelibrary', '0003_socialmediacard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernonauthfield',
            name='last_movement',
            field=models.SlugField(max_length=200),
        ),
    ]
