# Generated by Django 4.2.2 on 2023-06-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movelibrary', '0003_rename_movementlibrary_movement_rename_tags_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='directions',
            field=models.TextField(default=''),
        ),
    ]
