# Generated by Django 4.2.2 on 2023-07-18 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movelibrary', '0004_alter_usernonauthfield_last_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernonauthfield',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
