# Generated by Django 4.2.2 on 2023-06-15 14:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movelibrary', '0006_usermovement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMovement',
            new_name='UserOneRepMax',
        ),
    ]
