# Generated by Django 4.2.2 on 2023-06-15 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movelibrary', '0007_rename_usermovement_useronerepmax'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMovementNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_notes', models.TextField()),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movelibrary.movement')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
