# Generated by Django 4.2.2 on 2023-06-17 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movelibrary', '0008_usermovementnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernonauthfield',
            name='last_movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movelibrary.movement'),
        ),
    ]
