# Generated by Django 4.2.2 on 2023-06-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movelibrary', '0009_alter_usernonauthfield_last_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='one_rm',
            field=models.BooleanField(default=False),
        ),
    ]
