# Generated by Django 4.2.2 on 2023-06-23 10:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movelibrary', '0010_tag_one_rm'),
    ]

    operations = [
        migrations.AddField(
            model_name='useronerepmax',
            name='movement',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='movelibrary.movement'),
            preserve_default=False,
        ),
    ]
