# Generated by Django 4.2.2 on 2023-06-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('movelibrary', '0011_useronerepmax_movement'), ('movelibrary', '0012_remove_useronerepmax_movement')]

    dependencies = [
        ('movelibrary', '0010_tag_one_rm'),
    ]

    operations = [
    ]
