# Generated by Django 4.2.2 on 2023-06-23 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movelibrary', '0013_delete_useronerepmax'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOneRepMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_rep_max', models.IntegerField(default=0)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movelibrary.movement')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
