# Generated by Django 4.2.2 on 2023-06-27 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movelibrary', '0014_useronerepmax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useronerepmax',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_rm_list', to='movelibrary.movement'),
        ),
    ]
