# Generated by Django 4.2.2 on 2023-06-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movelibrary', '0015_alter_useronerepmax_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useronerepmax',
            name='one_rep_max',
            field=models.IntegerField(),
        ),
    ]
