# Generated by Django 4.2.2 on 2023-06-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movelibrary', '0016_alter_useronerepmax_one_rep_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovementnotes',
            name='movement_notes',
            field=models.TextField(default=''),
        ),
    ]
