# Generated by Django 4.2.2 on 2023-07-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movelibrary', '0017_alter_usermovementnotes_movement_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNonAuthField',
        ),
    ]
