# imports the Item class from the local models.py file
from .models import UserOneRepMax, User
# imports the forms library from django
from django import forms
from allauth.account.forms import SignupForm


# class calls on the Modelform class inside the forms library from django
class OneRmForm(forms.ModelForm):
    # class meta used here to establish the metadata of the form element
    class Meta:
        # the model is the imported Item model from models.py
        model = UserOneRepMax
        # then the fields are listed as a python list of strings
        # that match the variable names
        fields = ('one_rep_max',)


class CustomSignupForm(SignupForm):  # Form generated by ChatGPT
    first_name = forms.CharField(max_length=50, label='First Name')
    last_name = forms.CharField(max_length=50, label='Last Name')

    def save(self, request):
        user = super(CustomSignupForm, self).save(request)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        return user


class NameEditForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name',)
